# docker-compose.yml
version: '4'
services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758/serving
    ports:
      - 5000:5000
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: ift6758/streamlit
    ports:
      - 4000:4000
    environment:
      - PROVIDER_SERVICE_IP_ADDRESS=serving
      

     
