name: milestone_3
channels:
  - conda-forge
  - defaults
dependencies:
  - altair=5.0.1
  - annotated-types=0.6.0
  - anyio=4.6
  - appdirs=1.4.4
  - argon2-cffi=21.3.0
  - arrow-cpp=17.0.0
  - attrs=24.2.0
  - beautifulsoup4=4.12.3
  - blas=1.0
  - bleach=6.2.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - certifi=2024.8.30
  - cffi=1.17.1
  - click=8.1.7
  - contourpy=1.3.1
  - cycler=0.11.0
  - debugpy=1.6.7
  - decorator=5.1.1
  - expat=2.6.4
  - flask=3.0.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - gitdb=4.0.7
  - gitpython=3.1.43
  - h11=0.14.0
  - httpcore=1.0.2
  - httpx=0.27.0
  - idna=3.7
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipywidgets=7.8.1
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - json5=0.9.25
  - jsonschema=4.23.0
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - jupyter_server=2.14.1
  - jupyterlab=4.2.5
  - kiwisolver=1.4.4
  - lcms2=2.12
  - libdeflate=1.17
  - libpng=1.6.39
  - libsqlite
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lxml=5.3.0
  - matplotlib=3.9.2
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - notebook=7.2.2
  - numexpr=2.10.1
  - numpy=1.26.4
  - openssl=3.4.0
  - packaging=24.1
  - pandas=2.2.3
  - pillow=11.0.0
  - pip=24.2
  - plotly=5.24.1
  - protobuf=4.25.3
  - psutil=5.9.0
  - pyarrow=17.0.0
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.2.0
  - python=3.12.3
  - python-dateutil=2.9.0post0
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - requests=2.32.3
  - scikit-learn=1.5.1
  - scipy=1.14.1
  - seaborn=0.13.2
  - setuptools=75.1.0
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.45.3
  - streamlit=1.40.1
  - tenacity=9.0.0
  - terminado=0.17.1
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.2
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - wandb=0.19.1
  - wheel=0.44.0
  - widgetsnbextension=3.6.6
  - xz=5.4.6
  - zlib
  - zstd=1.5.6
  - pip:
      - backcall==0.2.0
      - docopt==0.6.2
      - ipython==8.12.3
      - pickleshare==0.7.5
      - pipreqs==0.5.0
      - python-dotenv==1.0.1
      - waitress==3.0.2
      - yarg==0.1.9