# Setup
title:               IFT 6758 - Projet de science de données
tagline:             'Analyse des données de hockey'
description:         'Projet de science de données sur les données de hockey permettant de prédire si une équipe va gagner'
url:                 ''
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
